=> 
[32m#<ShopDetail:0x00007f0c1f7a47c0[0m
 id: [36m[1mnil[0m,
 shop_name: [36m[1mnil[0m,
 country: [36m[1mnil[0m,
 address_line_1: [36m[1mnil[0m,
 address_line_2: [36m[1mnil[0m,
 zipcode: [36m[1mnil[0m,
 country_code: [36m[1mnil[0m,
 google_map_location: [36m[1mnil[0m,
 phone_number: [36m[1mnil[0m,
 created_at: [36m[1mnil[0m,
 updated_at: [36m[1mnil[0m[32m>[0m
